baseURL = "https://rodfuenzalida.com"
languageCode = "en-us"
title = "Rodrigo Fuenzalida"
theme = "ananke"
[params]
  custom_css = ["css/custom.css"]
  featured_image = "/images/video_bg.jpg"
  profile_image = "/images/profile3.jpg"